"""Unit tests for the analysis engine primitives."""

from __future__ import annotations

import pytest

from repolens_analysis import (
    classify,
    detect_language,
    duplication_ratio,
    is_test_path,
    parse_file,
    should_ignore,
)
from repolens_analysis.ast_engine import heuristic_file_summary
from repolens_analysis.git_history import classify_intent, message_quality_score
from repolens_shared import FileCategory


class TestLanguageDetection:
    @pytest.mark.parametrize(
        ("path", "expected"),
        [
            ("src/main.py", "python"),
            ("app/page.tsx", "tsx"),
            ("lib/util.ts", "typescript"),
            ("Main.java", "java"),
            ("core.cpp", "cpp"),
            ("Dockerfile", "dockerfile"),
            ("Makefile", "make"),
            ("notes.md", "markdown"),
        ],
    )
    def test_detects_by_extension(self, path, expected):
        assert detect_language(path) == expected

    def test_detects_by_shebang(self):
        assert detect_language("scripts/run", "#!/usr/bin/env python3") == "python"

    def test_unknown_returns_none_rather_than_guessing(self):
        assert detect_language("data.xyzzy") is None


class TestFileClassification:
    @pytest.mark.parametrize(
        "path",
        [
            "node_modules/react/index.js",
            ".venv/lib/python3.11/site-packages/x.py",
            "dist/bundle.js",
            "assets/logo.png",
            "static/app.min.js",
        ],
    )
    def test_ignores_dependency_and_build_output(self, path):
        ignored, reason = should_ignore(path)
        assert ignored, f"{path} should be ignored"
        assert reason

    def test_classifies_candidate_code(self):
        assert classify("src/service.py") == FileCategory.CANDIDATE_CODE

    def test_classifies_tests(self):
        assert classify("tests/test_service.py") == FileCategory.TEST_CODE
        assert classify("src/__tests__/service.spec.ts") == FileCategory.TEST_CODE

    def test_classifies_generated_code_by_banner(self):
        head = "// Code generated by protoc-gen-go. DO NOT EDIT.\n"
        assert classify("api/service.pb.go", head) == FileCategory.GENERATED_CODE

    def test_classifies_lock_file_as_dependency_not_candidate_code(self):
        assert classify("package-lock.json") == FileCategory.DEPENDENCY_CODE

    def test_classifies_manifests_as_configuration(self):
        assert classify("pyproject.toml") == FileCategory.CONFIGURATION

    def test_test_path_detection(self):
        assert is_test_path("tests/unit/test_x.py")
        assert is_test_path("src/foo.test.ts")
        assert not is_test_path("src/latest/foo.py")


class TestAstEngine:
    def test_extracts_python_entities_with_complexity(self):
        source = (
            "class Service:\n"
            '    """Doc."""\n'
            "    def handle(self, request):\n"
            "        if request.valid and request.size > 0:\n"
            "            for item in request.items:\n"
            "                try:\n"
            "                    yield item\n"
            "                except ValueError:\n"
            "                    continue\n"
            "        return None\n"
        )
        result = parse_file("service.py", source, "python")
        assert result.parsed
        names = {entity.symbol for entity in result.entities}
        assert {"Service", "handle"} <= names
        handle = next(e for e in result.entities if e.symbol == "handle")
        # if + boolean_operator + for + except = 4 decision points above the base.
        assert handle.complexity == 5
        assert handle.max_nesting == 3

    def test_counts_nesting_without_double_counting(self):
        source = "def f(x):\n    if x:\n        for i in x:\n            while i:\n                i -= 1\n"
        entity = parse_file("a.py", source, "python").entities[0]
        assert entity.max_nesting == 3

    @pytest.mark.parametrize(
        ("language", "source", "symbol"),
        [
            ("javascript", "export function greet(name) { return `hi ${name}`; }", "greet"),
            ("typescript", "export const add = (a: number, b: number): number => a + b;", "add"),
            ("java", "public class A { public int f(int x) { return x; } }", "f"),
            ("c", "int add(int a, int b) { return a + b; }", "add"),
            ("cpp", "class K { public: int m(int x) { return x; } };", "m"),
        ],
    )
    def test_parses_every_supported_language(self, language, source, symbol):
        result = parse_file(f"file.{language}", source, language)
        assert result.parsed
        assert symbol in {entity.symbol for entity in result.entities}

    def test_malformed_source_does_not_raise(self):
        result = parse_file("broken.py", "def f(:\n    return", "python")
        assert result.parse_error is None or isinstance(result.parse_error, str)
        assert result.has_errors or result.entities == []

    def test_unsupported_language_reports_unparsed_rather_than_empty(self):
        result = parse_file("main.go", "package main\nfunc main() {}\n", "go")
        assert result.parsed is False
        assert result.code_lines > 0

    def test_heuristic_summary_counts_line_kinds(self):
        result = heuristic_file_summary("x.go", "// comment\ncode()\n\n", "go")
        assert (result.comment_lines, result.code_lines, result.blank_lines) == (1, 1, 1)


class TestDuplicationDetection:
    def test_detects_duplicate_blocks_across_files(self):
        block = "\n".join(f"    value_{index} = compute(index_{index}, other_{index})" for index in range(8))
        ratio, examples = duplication_ratio({"a.py": block, "b.py": block})
        assert ratio > 0.4
        assert examples

    def test_unrelated_files_have_no_duplication(self):
        ratio, _ = duplication_ratio(
            {
                "a.py": "\n".join(f"    alpha_{i} = transform(source_{i})" for i in range(8)),
                "b.py": "\n".join(f"    beta_{i} = persist(record_{i}, store_{i})" for i in range(8)),
            }
        )
        assert ratio == 0.0


class TestCommitIntent:
    @pytest.mark.parametrize(
        ("message", "expected"),
        [
            ("fix: null pointer when parsing empty config", "fix"),
            ("refactor the auth service into two modules", "refactor"),
            ("add tests for the scoring engine", "test"),
            ("docs: explain the retry policy", "docs"),
            ("perf: cache the compiled patterns", "perf"),
            ("ci: run the suite on pull requests", "deploy"),
            ("Implement the posting rules", "feature"),
            ("update", "other"),
        ],
    )
    def test_classifies_intent(self, message, expected):
        assert classify_intent(message) == expected

    def test_message_quality_penalises_non_descriptive_messages(self):
        from repolens_analysis.git_collect import Commit
        from datetime import datetime, timezone

        def commit(message: str) -> Commit:
            return Commit(
                sha="a" * 40, author_name="A", author_email="a@example.com",
                committed_at=datetime.now(timezone.utc), message=message,
            )

        good, low_effort, _ = message_quality_score([
            commit("fix: reject postings where debit and credit are the same account"),
            commit("refactor: extract the retry policy into its own module"),
        ])
        poor, poor_low_effort, _ = message_quality_score([commit("update"), commit("fix")])
        assert good > poor
        assert low_effort == 0.0
        assert poor_low_effort == 1.0
