"""File filtering and classification.

Two jobs:

1. Decide whether a path is analysed at all (``should_ignore``).
2. Decide what a path *is* (``classify``) so that dependency and generated code
   is never attributed to the candidate.
"""

from __future__ import annotations

import re
from pathlib import PurePosixPath

from repolens_shared import FileCategory

from .languages import (
    DATA_LANGUAGES,
    DOC_LANGUAGES,
    MARKUP_LANGUAGES,
    detect_language,
    is_programming_language,
)

#: Directory names never walked. Vendored dependencies, build output, VCS data.
IGNORED_DIRECTORIES: frozenset[str] = frozenset(
    {
        ".git", ".hg", ".svn", "node_modules", "bower_components", "jspm_packages",
        "venv", ".venv", "env", ".env.d", "virtualenv", "__pycache__", ".mypy_cache",
        ".pytest_cache", ".ruff_cache", ".tox", ".nox", "site-packages",
        "dist", "build", "out", "target", "bin", "obj", "coverage", "htmlcov",
        ".next", ".nuxt", ".svelte-kit", ".turbo", ".parcel-cache", ".cache",
        "vendor", "third_party", "thirdparty", "external", "Pods",
        ".idea", ".vscode", ".gradle", ".terraform", ".serverless",
        "migrations/versions" ,
    }
)

#: Extensions that are binary or otherwise not text we can reason about.
BINARY_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tiff", ".svg",
        ".pdf", ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
        ".mp3", ".mp4", ".avi", ".mov", ".wav", ".flac", ".ogg", ".webm",
        ".woff", ".woff2", ".ttf", ".eot", ".otf",
        ".so", ".dll", ".dylib", ".exe", ".bin", ".o", ".a", ".class", ".pyc", ".pyd",
        ".db", ".sqlite", ".sqlite3", ".parquet", ".pkl", ".pickle", ".npy", ".npz",
        ".pt", ".pth", ".onnx", ".h5", ".safetensors", ".ckpt",
    }
)

#: Lock files: real artefacts but never candidate-authored code.
LOCK_FILES: frozenset[str] = frozenset(
    {
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb",
        "poetry.lock", "pdm.lock", "uv.lock", "Pipfile.lock", "Cargo.lock",
        "composer.lock", "gemfile.lock", "go.sum", "mix.lock",
    }
)

DEPENDENCY_MANIFESTS: frozenset[str] = frozenset(
    {
        "package.json", "requirements.txt", "requirements-dev.txt", "pyproject.toml",
        "setup.py", "setup.cfg", "Pipfile", "environment.yml", "Cargo.toml",
        "go.mod", "pom.xml", "build.gradle", "build.gradle.kts", "composer.json",
        "Gemfile", "pubspec.yaml", "mix.exs",
    }
)

_GENERATED_PATH_RE = re.compile(
    r"(^|/)("
    r"generated|__generated__|gen|autogen|auto_generated|"
    r"migrations|proto_gen|swagger|openapi_client|"
    r".*\.pb\.(go|py|js|ts)|.*_pb2(_grpc)?\.py|.*\.g\.dart|.*\.generated\.[a-z]+"
    r")(/|$)",
    re.IGNORECASE,
)

_GENERATED_HEADER_RE = re.compile(
    r"(@generated|do not edit|automatically generated|autogenerated|"
    r"this file was generated|code generated by)",
    re.IGNORECASE,
)

_TEST_PATH_RE = re.compile(
    r"(^|/)(tests?|__tests__|spec|specs|e2e|integration_tests?|testing)(/|$)"
    r"|(^|/)(test_[^/]+|[^/]+_test|[^/]+\.test|[^/]+\.spec|conftest)\.[a-z]+$",
    re.IGNORECASE,
)

_CONFIG_NAMES: frozenset[str] = frozenset(
    {
        ".gitignore", ".gitattributes", ".dockerignore", ".editorconfig", ".npmrc",
        ".nvmrc", ".prettierrc", ".eslintrc", ".eslintrc.js", ".eslintrc.json",
        "tsconfig.json", "jsconfig.json", "next.config.js", "next.config.mjs",
        "next.config.ts", "tailwind.config.js", "tailwind.config.ts", "vite.config.ts",
        "webpack.config.js", "rollup.config.js", "babel.config.js", "jest.config.js",
        "vitest.config.ts", "playwright.config.ts", "docker-compose.yml",
        "docker-compose.yaml", "dockerfile", "makefile", "procfile", "alembic.ini",
        "pytest.ini", "tox.ini", "mypy.ini", ".flake8", "ruff.toml",
    }
)

_DOC_NAMES: frozenset[str] = frozenset(
    {"readme", "contributing", "changelog", "license", "licence", "code_of_conduct",
     "security", "authors", "notice", "architecture", "roadmap"}
)


def should_ignore(path: str) -> tuple[bool, str | None]:
    """Return ``(ignored, reason)`` for a repository-relative POSIX path."""
    parts = PurePosixPath(path).parts
    for part in parts[:-1]:
        if part in IGNORED_DIRECTORIES:
            return True, f"inside ignored directory '{part}'"
    name = parts[-1] if parts else path
    if name in IGNORED_DIRECTORIES:
        return True, f"ignored directory '{name}'"
    suffix = PurePosixPath(name).suffix.lower()
    if suffix in BINARY_EXTENSIONS:
        return True, f"binary extension '{suffix}'"
    if name.endswith(".min.js") or name.endswith(".min.css") or name.endswith(".map"):
        return True, "minified or source-map artefact"
    return False, None


def is_lock_file(path: str) -> bool:
    return PurePosixPath(path).name.lower() in {n.lower() for n in LOCK_FILES}


def is_dependency_manifest(path: str) -> bool:
    return PurePosixPath(path).name in DEPENDENCY_MANIFESTS


def is_test_path(path: str) -> bool:
    return bool(_TEST_PATH_RE.search(path))


def looks_generated(path: str, head: str = "") -> bool:
    """Generated-code heuristic: path convention or an explicit banner in the
    first few lines. Both are conventions authors opt into, so this is a
    reliable signal rather than a guess about authorship."""
    if _GENERATED_PATH_RE.search(path):
        return True
    return bool(head) and bool(_GENERATED_HEADER_RE.search(head[:800]))


def classify(path: str, head: str = "") -> FileCategory:
    """Classify a repository file.

    ``head`` is the first ~1 KB of the file, used for generated-code banners and
    shebang-based language detection. It may be empty.
    """
    ignored, _ = should_ignore(path)
    if ignored:
        return FileCategory.IGNORED

    name = PurePosixPath(path).name
    lower_name = name.lower()
    stem = PurePosixPath(lower_name).stem

    if is_lock_file(path):
        return FileCategory.DEPENDENCY_CODE

    first_line = head.splitlines()[0] if head else None
    language = detect_language(path, first_line)

    if looks_generated(path, head):
        return FileCategory.GENERATED_CODE
    if is_test_path(path) and is_programming_language(language):
        return FileCategory.TEST_CODE
    if is_dependency_manifest(path) or lower_name in _CONFIG_NAMES:
        return FileCategory.CONFIGURATION
    if stem in _DOC_NAMES or language in DOC_LANGUAGES:
        return FileCategory.DOCUMENTATION
    if is_programming_language(language):
        return FileCategory.CANDIDATE_CODE
    if language in MARKUP_LANGUAGES:
        return FileCategory.CANDIDATE_CODE
    if language in DATA_LANGUAGES:
        return FileCategory.CONFIGURATION
    if language in ("dockerfile", "make", "cmake", "terraform"):
        return FileCategory.CONFIGURATION
    return FileCategory.ASSET
