"""Tutorial-derivation signals.

What this module can honestly do: recognise *unmodified scaffolding* and
*well-known starter-template shapes*, and combine that with cross-repository
similarity when a corpus is available.

What it cannot do: prove that a project follows a tutorial. There is no crawled
corpus of tutorial repositories bundled with RepoLens, so when the signals are
weak the classification is ``UNKNOWN`` rather than ``ORIGINAL``.

The output language is deliberately non-accusatory. The strongest statement the
system makes is that a candidate explanation is recommended.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from repolens_shared import OriginalityClassification


@dataclass(frozen=True, slots=True)
class TutorialSignal:
    id: str
    label: str
    weight: float
    patterns: tuple[str, ...] = ()
    paths: tuple[str, ...] = ()
    note: str = ""


#: Curated, auditable signal set. Every entry describes a *verifiable artefact*
#: left behind by a scaffolding tool or a widely-copied starter project.
TUTORIAL_SIGNALS: tuple[TutorialSignal, ...] = (
    TutorialSignal(
        "cra_scaffold", "Unmodified Create React App scaffolding", 0.28,
        patterns=(r"This project was bootstrapped with \[Create React App\]",
                  r"You can learn more in the \[Create React App documentation\]"),
        paths=("src/logo.svg", "src/reportWebVitals.js", "src/setupTests.js"),
        note="README and scaffold files are exactly as generated by create-react-app.",
    ),
    TutorialSignal(
        "next_scaffold", "Unmodified Next.js scaffolding", 0.26,
        patterns=(r"This is a \[Next\.js\]\(https://nextjs\.org\) project bootstrapped",
                  r"Get started by editing.*app/page",
                  r"Deploy on Vercel.*The easiest way to deploy your Next\.js app"),
        note="README is the default generated by create-next-app.",
    ),
    TutorialSignal(
        "vite_scaffold", "Unmodified Vite template", 0.22,
        patterns=(r"This template provides a minimal setup to get React working in Vite",
                  r"Expanding the ESLint configuration"),
    ),
    TutorialSignal(
        "django_scaffold", "Unmodified Django startproject layout", 0.18,
        patterns=(r"Django settings for \w+ project\.",
                  r"See https://docs\.djangoproject\.com/en/[\d.]+/topics/settings/"),
    ),
    TutorialSignal(
        "spring_initializr", "Unmodified Spring Initializr output", 0.18,
        patterns=(r"### Reference Documentation\s*\n\s*For further reference",
                  r"https://docs\.spring\.io/spring-boot/docs/.*/maven-plugin/reference/html"),
    ),
    TutorialSignal(
        "express_generator", "Express generator scaffolding", 0.18,
        paths=("bin/www", "views/error.jade", "views/error.pug"),
    ),
    TutorialSignal(
        "tutorial_placeholder_text", "Tutorial placeholder content retained", 0.16,
        patterns=(r"\bJohn Doe\b.*\bjohn(\.|@)doe\b", r"\byour[-_ ]api[-_ ]key[-_ ]here\b",
                  r"\bEdit `?src/App\.js`? and save to reload\b",
                  r"\bLearn React\b\s*</a>"),
    ),
    TutorialSignal(
        "step_numbered_comments", "Step-numbered instructional comments", 0.14,
        patterns=(r"(?im)^\s*(?://|#)\s*step\s*\d+\s*[:.\-]",
                  r"(?im)^\s*(?://|#)\s*(?:part|lesson|section)\s*\d+\s*[:.\-]"),
        note="Comments read as tutorial steps rather than as explanations of the code.",
    ),
    TutorialSignal(
        "tutorial_attribution", "Explicit tutorial attribution in the repository", 0.30,
        patterns=(r"(?i)\bfollow(?:ing|ed)?\s+(?:this|a|the)\s+(?:tutorial|course|guide|video)\b",
                  r"(?i)\bbased on\s+(?:this|the)\s+(?:tutorial|course|youtube)\b",
                  r"(?i)\b(?:freecodecamp|traversy|academind|net ?ninja|codewithharry)\b"),
        note="The repository itself states that it follows external material. This is "
             "disclosure, not misconduct, and should be read as such.",
    ),
)

_SCAFFOLD_ONLY_DIRS = ("src/", "app/", "public/")


@dataclass(slots=True)
class TutorialAssessment:
    classification: OriginalityClassification
    score: float
    confidence: float
    matched_signals: list[dict[str, object]] = field(default_factory=list)
    limitations: list[str] = field(default_factory=list)


def assess_tutorial_signals(
    texts: dict[str, str],
    all_paths: list[str],
    external_similarity: float | None = None,
    corpus_size: int = 0,
) -> TutorialAssessment:
    """Evaluate tutorial-derivation signals.

    ``external_similarity`` is the highest similarity found against *other*
    repositories in the local corpus, when one exists. With no corpus the
    assessment relies on scaffold signals alone and says so.
    """
    matched: list[dict[str, object]] = []
    total = 0.0
    path_set = set(all_paths)
    blob = "\n".join(texts.values())

    for signal in TUTORIAL_SIGNALS:
        hits: list[str] = []
        for pattern in signal.patterns:
            match = re.search(pattern, blob, re.MULTILINE)
            if match:
                hits.append(f"matched: {match.group(0)[:120].strip()}")
        for path in signal.paths:
            if path in path_set:
                hits.append(f"scaffold file present: {path}")
        if hits:
            total += signal.weight
            matched.append({
                "id": signal.id,
                "label": signal.label,
                "weight": signal.weight,
                "note": signal.note,
                "observations": hits[:4],
            })

    if external_similarity is not None and external_similarity >= 0.6:
        weight = 0.25 if external_similarity >= 0.8 else 0.15
        total += weight
        matched.append({
            "id": "corpus_similarity",
            "label": "High similarity to another analysed repository",
            "weight": weight,
            "note": "Similarity is to another repository in this deployment's corpus, which may "
                    "itself be legitimate shared or open-source code.",
            "observations": [f"maximum cross-repository similarity {external_similarity:.2f}"],
        })

    limitations = [
        "No crawled corpus of public tutorial repositories is bundled. Detection relies on "
        "scaffolding artefacts, explicit attribution and cross-repository similarity within this "
        "deployment.",
        "Using a framework's official starter template is normal practice. These signals describe "
        "what was left unmodified, not whether the candidate understands the code.",
    ]
    if corpus_size == 0:
        limitations.append(
            "No other repositories were available for cross-repository comparison during this run."
        )

    # Classification. UNKNOWN when there is simply not enough evidence either way.
    evidence_available = bool(texts) and (corpus_size > 0 or bool(matched))
    if total >= 0.45:
        classification = OriginalityClassification.STRONG_TUTORIAL_SIMILARITY
        confidence = min(0.8, 0.45 + total * 0.4)
    elif total >= 0.2:
        classification = OriginalityClassification.POSSIBLY_TUTORIAL_DERIVED
        confidence = 0.5 + total * 0.3
    elif not evidence_available:
        classification = OriginalityClassification.UNKNOWN
        confidence = 0.2
    else:
        classification = OriginalityClassification.ORIGINAL
        confidence = 0.55 if corpus_size else 0.4

    return TutorialAssessment(
        classification=classification,
        score=round(min(1.0, total), 4),
        confidence=round(confidence, 3),
        matched_signals=matched,
        limitations=limitations,
    )
