"""initial schema

Revision ID: e92381fcdd0e
Revises: 
Create Date: 2026-09-15 18:07:37.142108+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e92381fcdd0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer_failures',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_job_id', sa.String(length=32), nullable=True),
    sa.Column('repository_id', sa.String(length=32), nullable=True),
    sa.Column('analyzer', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('traceback_digest', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyzer_failures'))
    )
    op.create_index(op.f('ix_analyzer_failures_analysis_job_id'), 'analyzer_failures', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_analyzer_failures_analyzer'), 'analyzer_failures', ['analyzer'], unique=False)
    op.create_index(op.f('ix_analyzer_failures_created_at'), 'analyzer_failures', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyzer_failures_repository_id'), 'analyzer_failures', ['repository_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_time', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('github_accounts',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('github_user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('verified_emails', sa.JSON(), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_accounts')),
    sa.UniqueConstraint('user_id', 'github_user_id', name='uq_github_account')
    )
    op.create_index(op.f('ix_github_accounts_github_user_id'), 'github_accounts', ['github_user_id'], unique=False)
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('redirect_to', sa.String(length=500), nullable=True),
    sa.Column('intent', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states'))
    )
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_organizations_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_is_demo'), 'organizations', ['is_demo'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('candidates',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('github_login', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=300), nullable=True),
    sa.Column('resume_parsed', sa.JSON(), nullable=False),
    sa.Column('ai_disclosure', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_candidates_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidates_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_github_login'), 'candidates', ['github_login'], unique=False)
    op.create_index(op.f('ix_candidates_is_demo'), 'candidates', ['is_demo'], unique=False)
    op.create_index('ix_candidates_org_email', 'candidates', ['organization_id', 'email'], unique=False)
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('evaluation_policies',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_policies_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluation_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_policies')),
    sa.UniqueConstraint('policy_key', 'version', name='uq_policy_key_version')
    )
    op.create_index(op.f('ix_evaluation_policies_organization_id'), 'evaluation_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evaluation_policies_policy_key'), 'evaluation_policies', ['policy_key'], unique=False)
    op.create_index('ix_policies_org_current', 'evaluation_policies', ['organization_id', 'is_current'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('experience_level', sa.String(length=30), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('min_years_experience', sa.Integer(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('parse_notes', sa.JSON(), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['evaluation_policies.id'], name=op.f('fk_jobs_policy_id_evaluation_policies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_is_demo'), 'jobs', ['is_demo'], unique=False)
    op.create_index(op.f('ix_jobs_is_public'), 'jobs', ['is_public'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_table('repositories',
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('github_account_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('clone_url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('primary_language', sa.String(length=60), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('license_name', sa.String(length=120), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repo_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analyzed_sha', sa.String(length=64), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('github_metadata', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_repositories_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['github_account_id'], ['github_accounts.id'], name=op.f('fk_repositories_github_account_id_github_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_repositories_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('owner_user_id', 'full_name', name='uq_repository_owner_full_name')
    )
    op.create_index('ix_repositories_candidate', 'repositories', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_repositories_external_id'), 'repositories', ['external_id'], unique=False)
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_is_demo'), 'repositories', ['is_demo'], unique=False)
    op.create_index(op.f('ix_repositories_owner_user_id'), 'repositories', ['owner_user_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('requested_by_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('worker', sa.String(length=40), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_analysis_jobs_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_analysis_jobs_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_requested_by_id'), 'analysis_jobs', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index('ix_analysis_jobs_status_created', 'analysis_jobs', ['status', 'created_at'], unique=False)
    op.create_table('code_chunks',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('symbol', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('structure_signature', sa.String(length=64), nullable=False),
    sa.Column('fingerprints', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedder', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_code_chunks_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_chunks'))
    )
    op.create_index('ix_code_chunks_repo_file', 'code_chunks', ['repository_id', 'file_path'], unique=False)
    op.create_index(op.f('ix_code_chunks_repository_id'), 'code_chunks', ['repository_id'], unique=False)
    op.create_index('ix_code_chunks_signature', 'code_chunks', ['structure_signature'], unique=False)
    op.create_table('job_requirements',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('skill', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('matched_terms', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_requirements_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirements')),
    sa.UniqueConstraint('job_id', 'skill', name='uq_job_requirement_skill')
    )
    op.create_index(op.f('ix_job_requirements_job_id'), 'job_requirements', ['job_id'], unique=False)
    op.create_table('repository_analyses',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('analysis_job_id', sa.String(length=32), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('analyzer_version', sa.String(length=20), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('repository_score', sa.Float(), nullable=True),
    sa.Column('ownership_confidence', sa.Float(), nullable=True),
    sa.Column('ai_likelihood', sa.Float(), nullable=True),
    sa.Column('ai_classification', sa.String(length=40), nullable=True),
    sa.Column('ai_utilization', sa.Float(), nullable=True),
    sa.Column('originality', sa.String(length=40), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_analyses_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_analyses'))
    )
    op.create_index(op.f('ix_repository_analyses_analysis_job_id'), 'repository_analyses', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_repository_analyses_repository_id'), 'repository_analyses', ['repository_id'], unique=False)
    op.create_table('repository_branches',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_branches_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_branches')),
    sa.UniqueConstraint('repository_id', 'name', name='uq_repository_branch')
    )
    op.create_index(op.f('ix_repository_branches_repository_id'), 'repository_branches', ['repository_id'], unique=False)
    op.create_table('repository_commits',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('is_merge', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_commits_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_commits')),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_repository_commit_sha')
    )
    op.create_index(op.f('ix_repository_commits_author_email'), 'repository_commits', ['author_email'], unique=False)
    op.create_index('ix_repository_commits_date', 'repository_commits', ['repository_id', 'committed_at'], unique=False)
    op.create_index(op.f('ix_repository_commits_intent'), 'repository_commits', ['intent'], unique=False)
    op.create_index(op.f('ix_repository_commits_repository_id'), 'repository_commits', ['repository_id'], unique=False)
    op.create_table('repository_dependencies',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version_spec', sa.String(length=120), nullable=False),
    sa.Column('ecosystem', sa.String(length=30), nullable=False),
    sa.Column('manifest', sa.String(length=500), nullable=False),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_dependencies_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_dependencies'))
    )
    op.create_index('ix_repository_dependencies_name', 'repository_dependencies', ['repository_id', 'name'], unique=False)
    op.create_index(op.f('ix_repository_dependencies_repository_id'), 'repository_dependencies', ['repository_id'], unique=False)
    op.create_table('repository_files',
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('skipped_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_files_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_files')),
    sa.UniqueConstraint('repository_id', 'path', name='uq_repository_file_path')
    )
    op.create_index(op.f('ix_repository_files_category'), 'repository_files', ['category'], unique=False)
    op.create_index('ix_repository_files_hash', 'repository_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_repository_files_language'), 'repository_files', ['language'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=True),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('job_match', sa.Float(), nullable=True),
    sa.Column('ownership_confidence', sa.Float(), nullable=True),
    sa.Column('ai_likelihood', sa.Float(), nullable=True),
    sa.Column('ai_utilization', sa.Float(), nullable=True),
    sa.Column('ai_classification', sa.String(length=40), nullable=True),
    sa.Column('originality', sa.String(length=40), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_reasons', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=False),
    sa.Column('skill_matches', sa.JSON(), nullable=False),
    sa.Column('engineering_dna', sa.JSON(), nullable=False),
    sa.Column('resume_consistency', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.JSON(), nullable=True),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], name=op.f('fk_evaluations_analysis_id_repository_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_evaluations_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_evaluations_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evaluations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['evaluation_policies.id'], name=op.f('fk_evaluations_policy_id_evaluation_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_evaluations_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_evaluations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index(op.f('ix_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluations_is_demo'), 'evaluations', ['is_demo'], unique=False)
    op.create_index('ix_evaluations_job_candidate', 'evaluations', ['job_id', 'candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluations_job_id'), 'evaluations', ['job_id'], unique=False)
    op.create_index(op.f('ix_evaluations_organization_id'), 'evaluations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evaluations_repository_id'), 'evaluations', ['repository_id'], unique=False)
    op.create_index('ix_evaluations_status', 'evaluations', ['verification_status'], unique=False)
    op.create_index(op.f('ix_evaluations_user_id'), 'evaluations', ['user_id'], unique=False)
    op.create_table('security_findings',
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('masked_value', sa.String(length=200), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('cwe', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], name=op.f('fk_security_findings_analysis_id_repository_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_security_findings_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_findings'))
    )
    op.create_index('ix_security_findings_analysis', 'security_findings', ['analysis_id', 'severity'], unique=False)
    op.create_index(op.f('ix_security_findings_analysis_id'), 'security_findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_security_findings_repository_id'), 'security_findings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_security_findings_severity'), 'security_findings', ['severity'], unique=False)
    op.create_table('similarity_results',
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('repository_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('mechanism', sa.String(length=30), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('source_file', sa.String(length=1000), nullable=False),
    sa.Column('source_symbol', sa.String(length=300), nullable=False),
    sa.Column('matched_repository_id', sa.String(length=32), nullable=True),
    sa.Column('matched_repository_name', sa.String(length=300), nullable=True),
    sa.Column('matched_file', sa.String(length=1000), nullable=True),
    sa.Column('matched_symbol', sa.String(length=300), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['repository_analyses.id'], name=op.f('fk_similarity_results_analysis_id_repository_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_similarity_results_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similarity_results'))
    )
    op.create_index('ix_similarity_results_analysis', 'similarity_results', ['analysis_id', 'similarity'], unique=False)
    op.create_index(op.f('ix_similarity_results_analysis_id'), 'similarity_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_similarity_results_repository_id'), 'similarity_results', ['repository_id'], unique=False)
    op.create_table('evaluation_scores',
    sa.Column('evaluation_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_scores_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_scores')),
    sa.UniqueConstraint('evaluation_id', 'category', name='uq_evaluation_score')
    )
    op.create_index(op.f('ix_evaluation_scores_evaluation_id'), 'evaluation_scores', ['evaluation_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evaluation_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supports', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('analyzer', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evidence_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_evaluation_category', 'evidence', ['evaluation_id', 'category'], unique=False)
    op.create_index(op.f('ix_evidence_evaluation_id'), 'evidence', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    op.create_table('human_overrides',
    sa.Column('evaluation_id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_key', sa.String(length=80), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_human_overrides_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_human_overrides_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_overrides'))
    )
    op.create_index(op.f('ix_human_overrides_evaluation_id'), 'human_overrides', ['evaluation_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('evaluation_id', sa.String(length=32), nullable=True),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('repository_id', sa.String(length=32), nullable=True),
    sa.Column('interviewer_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_interview_sessions_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_interview_sessions_evaluation_id_evaluations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], name=op.f('fk_interview_sessions_interviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_interview_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_interview_sessions_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions'))
    )
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_evaluation_id'), 'interview_sessions', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_is_demo'), 'interview_sessions', ['is_demo'], unique=False)
    op.create_index(op.f('ix_interview_sessions_organization_id'), 'interview_sessions', ['organization_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('evaluation_id', sa.String(length=32), nullable=True),
    sa.Column('repository_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('expected_gain', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_recommendations_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_recommendations_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_evaluation_id'), 'recommendations', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_recommendations_repository_id'), 'recommendations', ['repository_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('reviewer_notes',
    sa.Column('evaluation_id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('visible_to_candidate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviewer_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_reviewer_notes_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_notes'))
    )
    op.create_index(op.f('ix_reviewer_notes_evaluation_id'), 'reviewer_notes', ['evaluation_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('repository_id', sa.String(length=32), nullable=True),
    sa.Column('evaluation_id', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('anchors', sa.JSON(), nullable=False),
    sa.Column('expected_points', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('generator_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_interview_questions_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_interview_questions_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_questions_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions'))
    )
    op.create_index(op.f('ix_interview_questions_evaluation_id'), 'interview_questions', ['evaluation_id'], unique=False)
    op.create_index('ix_interview_questions_repo_category', 'interview_questions', ['repository_id', 'category'], unique=False)
    op.create_index(op.f('ix_interview_questions_repository_id'), 'interview_questions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['session_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('assessed_by', sa.String(length=40), nullable=False),
    sa.Column('reviewer_score', sa.Float(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('fk_interview_answers_question_id_interview_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_answers_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_answers'))
    )
    op.create_index(op.f('ix_interview_answers_question_id'), 'interview_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_interview_answers_session_id'), 'interview_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answers_session_id'), table_name='interview_answers')
    op.drop_index(op.f('ix_interview_answers_question_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_repository_id'), table_name='interview_questions')
    op.drop_index('ix_interview_questions_repo_category', table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_evaluation_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_reviewer_notes_evaluation_id'), table_name='reviewer_notes')
    op.drop_table('reviewer_notes')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_repository_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_evaluation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_interview_sessions_organization_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_is_demo'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_evaluation_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_human_overrides_evaluation_id'), table_name='human_overrides')
    op.drop_table('human_overrides')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evaluation_id'), table_name='evidence')
    op.drop_index('ix_evidence_evaluation_category', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_evaluation_scores_evaluation_id'), table_name='evaluation_scores')
    op.drop_table('evaluation_scores')
    op.drop_index(op.f('ix_similarity_results_repository_id'), table_name='similarity_results')
    op.drop_index(op.f('ix_similarity_results_analysis_id'), table_name='similarity_results')
    op.drop_index('ix_similarity_results_analysis', table_name='similarity_results')
    op.drop_table('similarity_results')
    op.drop_index(op.f('ix_security_findings_severity'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_repository_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_analysis_id'), table_name='security_findings')
    op.drop_index('ix_security_findings_analysis', table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_evaluations_user_id'), table_name='evaluations')
    op.drop_index('ix_evaluations_status', table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_repository_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_organization_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_job_id'), table_name='evaluations')
    op.drop_index('ix_evaluations_job_candidate', table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_is_demo'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_candidate_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_language'), table_name='repository_files')
    op.drop_index('ix_repository_files_hash', table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_category'), table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index(op.f('ix_repository_dependencies_repository_id'), table_name='repository_dependencies')
    op.drop_index('ix_repository_dependencies_name', table_name='repository_dependencies')
    op.drop_table('repository_dependencies')
    op.drop_index(op.f('ix_repository_commits_repository_id'), table_name='repository_commits')
    op.drop_index(op.f('ix_repository_commits_intent'), table_name='repository_commits')
    op.drop_index('ix_repository_commits_date', table_name='repository_commits')
    op.drop_index(op.f('ix_repository_commits_author_email'), table_name='repository_commits')
    op.drop_table('repository_commits')
    op.drop_index(op.f('ix_repository_branches_repository_id'), table_name='repository_branches')
    op.drop_table('repository_branches')
    op.drop_index(op.f('ix_repository_analyses_repository_id'), table_name='repository_analyses')
    op.drop_index(op.f('ix_repository_analyses_analysis_job_id'), table_name='repository_analyses')
    op.drop_table('repository_analyses')
    op.drop_index(op.f('ix_job_requirements_job_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index('ix_code_chunks_signature', table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_repository_id'), table_name='code_chunks')
    op.drop_index('ix_code_chunks_repo_file', table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index('ix_analysis_jobs_status_created', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_requested_by_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_repositories_owner_user_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_is_demo'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_external_id'), table_name='repositories')
    op.drop_index('ix_repositories_candidate', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_public'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_demo'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('ix_policies_org_current', table_name='evaluation_policies')
    op.drop_index(op.f('ix_evaluation_policies_policy_key'), table_name='evaluation_policies')
    op.drop_index(op.f('ix_evaluation_policies_organization_id'), table_name='evaluation_policies')
    op.drop_table('evaluation_policies')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_index('ix_candidates_org_email', table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_demo'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_github_login'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_demo'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_github_user_id'), table_name='github_accounts')
    op.drop_table('github_accounts')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_analyzer_failures_repository_id'), table_name='analyzer_failures')
    op.drop_index(op.f('ix_analyzer_failures_created_at'), table_name='analyzer_failures')
    op.drop_index(op.f('ix_analyzer_failures_analyzer'), table_name='analyzer_failures')
    op.drop_index(op.f('ix_analyzer_failures_analysis_job_id'), table_name='analyzer_failures')
    op.drop_table('analyzer_failures')
    # ### end Alembic commands ###
